### PR TITLE
Return self in .fit() in ExponentiatedGradient

### PR DESCRIPTION
**Pull request by koaning**
The `.fit()` method currently doesn't return `self`. This PR changes that.

### CODE REVIEW

**Review by romanlutz — APPROVED** [review]
Thanks!

**Comment by romanlutz** [comment]
Interestingly, this failed the doc build because now this creates a return value.
```
File "quickstart.rst", line 190, in quickstart
Failed example:
    mitigator.fit(X, y_true, sensitive_features=sex)
Expected nothing
Got:
    ExponentiatedGradient(constraints=<fairlearn.reductions._moments.utility_parity.DemographicParity object at 0x7f9906ebe358>,
                          estimator=DecisionTreeClassifier(max_depth=4,
                                                           min_samples_leaf=10),
                          nu=0.0008201769357601916)
```
You can abbreviate the hex address with `...` and I think the same with the `nu` value as `nu=0.00...`. Or if you don't know what I mean just let me know and I'll push a quick commit onto your branch. :-)

**Comment by koaning** [comment]
I'm not 100% sure I follow so ues, feel free to make a small PR.

**Comment by romanlutz** [comment]
> I'm not 100% sure I follow so yes, feel free to make a small PR.

@koaning I just added the output your `return` addition produces to the quickstart code. This should pass all gates.

@MiroDudik @riedgar-ms @hildeweerts can one of you merge the PR (or add comments if you have any!). Thanks!

**Pull request merged**
