### PR TITLE
DOC Add jupyterlite button to the examples

### PR DESCRIPTION
**Pull request by TamaraAtanasoska**
## Description
Closes https://github.com/fairlearn/fairlearn/issues/764 and https://github.com/fairlearn/fairlearn/pull/870, clarification for the reasoning here: https://github.com/fairlearn/fairlearn/pull/870#issuecomment-2441832544. 

@romanlutz please take a look if possible as the issue was yours. 

## Tests

- [x] no new tests required
- [ ] new tests added
- [ ] existing tests adjusted

## Documentation

- [ ] no documentation changes needed
- [ ] user guide added or updated
- [ ] API docs added or updated
- [x] example notebook added or updated

## Screenshots

Screenshot 2024-10-29 at 16 14 19

Screenshot 2024-10-29 at 16 13 47

### CODE REVIEW

**Comment by TamaraAtanasoska** [comment]
@hildeweerts @romanlutz  I converted this to draft atm while I explore some additional things

**Comment by TamaraAtanasoska** [comment]
not sure what git did there, but my editor kept the files content that were deleted in my first commit. I had a minute to check, and this works now :) I tested most examples and they work as expected, the only issue are notebooks where `pytorch` is necessary, as it can't be installed by `pyodide`. maybe @adrinjalali know how to go around this, or those need to be only downloaded?

@hildeweerts this is the while setup, git tricked me 😄

**Review by adrinjalali — APPROVED** [review]
LGTM. We're not gonna want to support DL frameworks here anyway. They'd be too large to download for the browser tab.

**Comment by TamaraAtanasoska** [comment]
> LGTM. We're not gonna want to support DL frameworks here anyway. They'd be too large to download for the browser tab.

Cool, makes sense. I added a bit warning the notebook is just for preview and they can't run it when it contains `torch` in [1b2df46](https://github.com/fairlearn/fairlearn/pull/1422/commits/1b2df466bcb5204fa165299ca0e7b8ed40f43cff)

**Pull request merged**
