### PR TITLE
Merge pull request #1 from fairlearn/master

### PR DESCRIPTION
**Pull request by srayagarwal**
Update my local repo

### CODE REVIEW

**Comment by kevinrobinson** [comment]
@srayagarwal fyi it looks like there's nothing in here, maybe this is from a git mix up?

**Comment by srayagarwal** [comment]
@kevinrobinson Hi, update my repo with a new notebook. Please confirm

**Comment by kevinrobinson** [comment]
@srayagarwal You can verify this yourself in the GitHub web UI at `https://github.com/fairlearn/fairlearn/pull/496`, click on the tabs for "commits" and "changes" to see what is included in the pull request:

Screen Shot 2020-06-19 at 11 18 00 AM

**Comment by srayagarwal** [comment]
@kevinrobinson Thanks. Just wanted to confirm as last time the commit didnt go through properly

**Comment by kevinrobinson** [comment]
Sure, https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/proposing-changes-to-your-work-with-pull-requests might be helpful to check out too!

**Comment by riedgar-ms** [comment]
I'm not quite sure what this is supposed to be doing. There are no changed files, yet it's bringing in a commit from a fork?

**Comment by srayagarwal** [comment]
I uploaded the latest version of the notebook with some changes as compared to the last version

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by romanlutz** [comment]
@srayagarwal you probably meant to add to your other PR? Closing this one.

**Pull request closed without merging**
