### PR TITLE
Changed the copyright year

### PR DESCRIPTION
**Pull request by Daniel-olaO**
## Tests

- [ ] no new tests required
- [ ] new tests added
- [ ] existing tests adjusted

## Documentation

- [ ] no documentation changes needed
- [ ] user guide added or updated
- [ ] API docs added or updated
- [ ] example notebook added or updated

### CODE REVIEW

**Comment by Daniel-olaO** [comment]
close #1232

**Comment by adrinjalali** [comment]
thanks for the PR.

I'm not sure if we're pushing this page after merge to the docs: https://github.com/fairlearn/fairlearn/blob/main/.circleci/push_doc.sh

**Comment by Daniel-olaO** [comment]
No problem, just let me know if there any issue that I can work on

**Comment by hildeweerts** [comment]
@riedgar-ms @LeJit do you know whether this page is pushed after merge?

**Comment by riedgar-ms** [comment]
I don't believe it has been since @adrinjalali changed the docs so we only built the latest version on each merge

**Review by hildeweerts — APPROVED** [review]
I think we can merge this PR and open a new issue to deal with pushing the static landing page after a merge. WDYT @adrinjalali @riedgar-ms

**Comment by riedgar-ms** [comment]
It'll have to be merged here first before we can push to the website repo.

**Review by riedgar-ms — APPROVED** [review]

**Review by romanlutz — APPROVED** [review]

**Pull request merged**
