### PR TITLE
Connection update for PyPI Release Pipeline

### PR DESCRIPTION
**Pull request by riedgar-ms**
Updating the PyPI release pipeline to use the `TwineAuthenticate` task, rather than fetching things from Azure KeyVault.

### CODE REVIEW

**Comment by romanlutz** [comment]
> Updating the PyPI release pipeline to use the `TwineAuthenticate` task, rather than fetching things from Azure KeyVault.

Can you describe what's better about TwineAuthenticate? I'm not familiar with it. Does that mean we should delete the keyvault and it's credentials?

**Comment by riedgar-ms** [comment]
The TwineAuthenticate task bundles together the credentials and endpoint for a PyPI upload (or to a private feed). Yes, it means that we would be able to delete the KeyVault.

**Comment by romanlutz** [comment]
> The TwineAuthenticate task bundles together the credentials and endpoint for a PyPI upload (or to a private feed). Yes, it means that we would be able to delete the KeyVault.

I guess I'm still not sure where the secrets are actually stored then. It seems like we're doing away with the KeyVault, but where is the info stored. That's not clear to me from looking at the code.

**Comment by riedgar-ms** [comment]
I imagine that the secrets are stored in a similar way to the secret which allows use of the service principal which connects to the KeyVault.

**Comment by romanlutz** [comment]
> I imagine that the secrets are stored in a similar way to the secret which allows use of the service principal which connects to the KeyVault.

OK now I'm even more confused. Where are they actually stored? Is it in ADO? The current pipeline handles this by ADO having a service connection that has access to the KeyVault.

**Comment by riedgar-ms** [comment]
> > I imagine that the secrets are stored in a similar way to the secret which allows use of the service principal which connects to the KeyVault.
> 
> OK now I'm even more confused. Where are they actually stored? Is it in ADO? The current pipeline handles this by ADO having a service connection that has access to the KeyVault.

But the service connection must contain some sort of secret for access to the service principal. Where's that stored?

**Pull request merged**
