### PR TITLE
MNT Add caching for branches in the doc and doctest CircleCI builds

### PR DESCRIPTION
**Pull request by TamaraAtanasoska**
## Description
This PR follows up on the discussion in #703, specifically [this comment](https://github.com/fairlearn/fairlearn/issues/703#issuecomment-2200224570), in hopes to have less CI failures when OpenML datasets aren't available to download in order to run the examples.

More information about the CircleCI process [here](https://circleci.com/docs/caching/).
Inspiration taken from [scikit-learn](https://github.com/scikit-learn/scikit-learn/blob/main/.circleci/config.yml#L34-L49).

## Tests

- [x] no new tests required
- [ ] new tests added
- [ ] existing tests adjusted

## Documentation

- [x] no documentation changes needed
- [ ] user guide added or updated
- [ ] API docs added or updated
- [ ] example notebook added or updated

### CODE REVIEW

**Comment by TamaraAtanasoska** [comment]
@adrinjalali I forgot to tag you in this PR

**Review by adrinjalali — COMMENTED** [review]
Thanks @TamaraAtanasoska , how does one check if this is working?

**Comment by TamaraAtanasoska** [comment]
One can see it try to restore the cache before everything is run and then
save to cache at the end:
https://app.circleci.com/pipelines/github/fairlearn/fairlearn/4191/workflows/3f244df2-2bee-42ba-972f-4122d54252cf/jobs/8375?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary

It seems in this instance it wasn’t able to restore any cache, but it saved
it and the end. Does the folder I picked to save into persist between
builds (temp-fairlearn)?

**Comment by adrinjalali** [comment]
at least for `fetch_openml` isn't that `~/scikit_learn_data`?

**Comment by TamaraAtanasoska** [comment]
> ~/scikit_learn_data

Right, good catch. I read that file, but `data_home` is defined [somewhere else](https://github.com/scikit-learn/scikit-learn/blob/0dba98f1eb7edc893e26c36d54519386a265467d/sklearn/datasets/_base.py#L43) and the exact name somehow slipped. I can use the default used by scikit-learn to not have to add extra variable settings, it was in the original template I used too.

**Review by adrinjalali — APPROVED** [review]

**Pull request merged**
