### PR TITLE
DOC move adversarial examples

### PR DESCRIPTION
**Pull request by adrinjalali**
This moves the adversarial examples from the tutorial to the example gallery with a few changes and adds `torch` to the dev requirements.

This also changes the signature of callbacks, not really sure how to handle the deprecation here, if we want to.

@SeanMcCarren @fairlearn/fairlearn-maintainers

### CODE REVIEW

**Review by romanlutz — APPROVED** [review]
Lgtm. Can't say I have an opinion on the questions you asked in the description.

**Comment by TamaraAtanasoska** [comment]
is it time to move this forward? it seems like a great change.

**Comment by riedgar-ms** [comment]
Happy to see this updated and merged.

**Comment by adrinjalali** [comment]
So the pytorch issue is this: https://github.com/skorch-dev/skorch/issues/1071

**Comment by adrinjalali** [comment]
@TamaraAtanasoska this is finally green (or blue of you have colorblind friendly colors like me 😁 )

Wanna approve and merge with your new shiny merge rights?

**Review by TamaraAtanasoska — APPROVED** [review]

**Pull request merged**
