### PR TITLE
FIX add utils module in 0.7.0 release

### PR DESCRIPTION
**Pull request by romanlutz**
#859 added a `utils` directory without `__init__.py` file which made the release pipeline break. This addition fixes it so that we can proceed with release v0.7.0. The same change will be merged into `main` in a separate PR (with a few additional small adjustments).

By pulling in changes from main to get the #878 changes into this PR I used the wrong command (merge instead of cherry-pick) which added PRs #873 #787  #871 and #806 to this PR. Since they all improve the docs this means that our doc page for v0.7.0 will be improved which I consider to be a bonus. Otherwise people won't see those changes until the next release (except if they use the `main` version of the website). If someone has objections please voice them in this thread!

@fairlearn/fairlearn-maintainers please review.

Signed-off-by: Roman Lutz <rolutz@microsoft.com>

### CODE REVIEW

**Comment by adrinjalali** [comment]
Could you explain why it made the release break?

**Comment by romanlutz** [comment]
> Could you explain why it made the release break?

Yes! See this pipeline https://dev.azure.com/responsibleai/fairlearn/_build/results?buildId=12191&view=results

Errors during test collection when using the created wheel:
```

________________________ ERROR collecting test session _________________________
/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/_pytest/config/__init__.py:415: in _importconftest
    return self._conftestpath2mod[conftestpath]
E   KeyError: local('/home/vsts/work/1/s/test/unit/postprocessing/conftest.py')

During handling of the above exception, another exception occurred:
/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/_pytest/config/__init__.py:421: in _importconftest
    mod = conftestpath.pyimport()
/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/py/_path/local.py:704: in pyimport
    __import__(modname)
/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:149: in exec_module
    exec(co, module.__dict__)
test/unit/postprocessing/conftest.py:11: in <module>
    from fairlearn.postprocessing._threshold_operation import ThresholdOperation
/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/fairlearn/postprocessing/__init__.py:10: in <module>
    from ._threshold_optimizer import ThresholdOptimizer  # noqa: F401
/opt/hostedtoolcache/Python/3.6.13/x64/lib/python3.6/site-packages/fairlearn/postprocessing/_threshold_optimizer.py:31: in <module>
    from ..utils._common import _get_soft_predictions
E   ModuleNotFoundError: No module named 'fairlearn.utils'
```
My suspicion was that the reason is that the `__init__.py` file was missing, so I created this branch and reran just the wheel creation and tests. That worked, so I opened the PR. The part that I don't understand is why it doesn't fail in the tests *before* the wheel is built. There must be some subtle difference between running something as an installed package vs. in editable mode from within the same directory structure (?)

**Review by hildeweerts — APPROVED** [review]

**Comment by adrinjalali** [comment]
Could we please cherry pick https://github.com/fairlearn/fairlearn/pull/878 instead of merging this one?

**Comment by romanlutz** [comment]
> Could we please cherry pick #878 instead of merging this one? As in, you could have a PR which cherry picks a few commits from `main` into the release branch, and we can review and merge that one.

The result will be the same as this PR, as you can verify through: https://github.com/fairlearn/fairlearn/compare/main...rolutz/release_070_fix

Are you suggesting this since cherry-pick is cleaner than merge?

**Comment by adrinjalali** [comment]
I know the result is the same, but it's cleaner if we don't do _development_ on the release branches.

**Pull request closed without merging**
