### PR TITLE
MNT Release step 3: Apply versioning changes for the website to main

### PR DESCRIPTION
**Pull request by TamaraAtanasoska**
## Description
This PR applies the following changes outlined in the guidelines:
```
- Update the version in __init__.py to x.y+1.z.dev0
- Update the version in docs/static_landing_page/js/landing_page.js so that all the links point to the new release
- Update the docs/_static/versions.json file
- Create a new file vx.y+1.z.rst in docs/user_guide/installation_and_version_guide
```
@adrinjalali 

## Tests

- [x] no new tests required
- [ ] new tests added
- [ ] existing tests adjusted

## Documentation

- [ ] no documentation changes needed
- [x] user guide added or updated
- [ ] API docs added or updated
- [ ] example notebook added or updated

### CODE REVIEW

**Review by adrinjalali — COMMENTED** [review]
I think you can also remove the ones older than 0.7

**Comment by TamaraAtanasoska** [comment]
> I think you can also remove the ones older than 0.7

Could we maybe ask folks in the next meeting and do it the next release? I am sure people don't mind, just to make this more democratic as it is a bit of a change.

**Comment by adrinjalali** [comment]
Those releases are from 2021 and older, I'm sure we can remove them from the website (we're not removing their packages from pypi). cc @fairlearn/fairlearn-maintainers

**Comment by riedgar-ms** [comment]
I'd be happy removing those older versions from the website for sure.

**Comment by adrinjalali** [comment]
I don't think we should remove the changelog history here. Simply removing the links in the version navigator is enough. The changelog can stay there for a historical view.

**Comment by TamaraAtanasoska** [comment]
@adrinjalali I just came back home - fixed. I am AFK until Monday, if something isn't to your liking in the fix commit, please push a version that makes more sense, as well if something is off after the merge. I prepared some communication material, but that would have to wait until I am back.

**Review by adrinjalali — APPROVED** [review]

**Pull request merged**
