### PR TITLE
Notebook: First draft towards consumer lending

### PR DESCRIPTION
**Pull request by kevinrobinson**
This is a minimal first draft at a consumer lending notebook, based on conversations and notes from https://hackmd.io/@nK2k69tBRwSK3K8_DNmRnQ/BJ_6y9g6L.

As discussed, there's some bits we'll still need to figure out about the deployment context in order to work through this, and some other offline conversations too.

In this pull request, I'm just trying to do the chore of translating discussion and notes into something that can resemble a notebook.  I very much get that it's still up in the air whether this kind of notebook is a good fit for the project (eg, in terms of https://github.com/fairlearn/fairlearn/pull/490 or https://fairlearn.github.io/contributor_guide/how_to_talk_about_fairness.html).  but hopefully it will help with working through all that productively if we have something more concrete to look at :)

### CODE REVIEW

**Comment by kevinrobinson** [comment]
Also, my understanding was that folks thought it would make more sense to work forward in this direction, since there may be even ways to get more input from partners with more expertise in this domain.

So while there may be perspectives in the critique in https://github.com/fairlearn/fairlearn/issues/418 that are useful to roll forward here, much of that may not apply once we work through more specifics on the deployment context in this draft.

**Comment by kevinrobinson** [comment]
In working forward on this, I thought it was important to bring up that while the open source Fairlearn project may choose to focus on consumer lending as an example, this [microsoft.com article about Fairlearn](https://customers.microsoft.com/en-US/story/809460-ey-partner-professional-services-azure-machine-learning-fairlearn) presents quite a different context.  The lead quote is that:

> We see... our partnership with Microsoft as critical to driving increased adoption and acceptance of AI from the regulators.

The article describes using Fairlearn on "real mortgage adjudication data" and not consumer loans.  The regulatory context is ambiguous in the article, but in the US this difference matters since different federal regulations apply to mortgage lending.

Further, there's another important bit of context on mortgage lending to consider that specifically relates to third-party algorithmic systems.  Last summer, the US Department of Housing and Urban Development proposed a rule change that would make specific regulatory exceptions for mortgage lending decisions that are made by third party algorithmic systems.  Some familiar names have submitted [public comments](https://twitter.com/aselbst/status/1185232906148601856) and written [articles](https://slate.com/technology/2019/08/hud-disparate-impact-discrimination-algorithm.html) on this.  Here's an excerpt from the article by Andrew Selbst (with my emphasis added):

> [The] new proposed rule... [would] give landlords and mortgage lenders a recipe to discriminate by algorithm... First, the proposal allows landlords to use an algorithm as long as its inputs are not “substitutes or close proxies” for protected characteristics and as long as it’s predictive of what it purports to predict—or a “neutral third party” certifies that fact... Second, the landlord is also immunized from any discrimination claim **if he uses a tool developed and maintained by a recognized third party.** These safe harbors supposedly ensure that a model is legitimate and the landlord has not himself “caused” the discriminatory outcome.

And an excerpt from the [public comments](https://twitter.com/aselbst/status/1185232906148601856) by Selbst and Gilman:

> Permitting a defense showing that the model is the fault of some third party that determines industry standards creates functional immunity because there is no mention that the industry standard be anti-discriminatory, and the third party likely cannot be sued under the Fair Housing Act. Permitting “an objective and unbiased neutral third party” to validate the truth of the first defense and that the algorithm is “statistically sound” fails to account for algorithmic discrimination for the same reason the first defense does. Though the NPRM claims that the “section is not intended to provide a special exemption for parties who use algorithmic models,” 84 Fed. Reg. 42859, that is precisely the effect of the rule as written.

So when considering this context, and thinking about how Fairlearn might be able to contribute to assessing and mitigating real world harms for real people in the context of fair lending, I interpret the [microsoft.com article about Fairlearn](https://customers.microsoft.com/en-US/story/809460-ey-partner-professional-services-azure-machine-learning-fairlearn) a bit differently.

I am sure there is a ton of complexity in all of this work, but @MiroDudik @hannawallach if these were not things you'd come across yet, I thought it might be helpful to raise them for your consideration.  While @MiroDudik I heard you suggesting that a notebook for Fairlearn might be better suited for consumer lending, and that might make a good first deployment context to focus on, I think it's important to say that the current marketing of Fairlearn has actually been aimed at mortgage lending.

Thanks for listening, and for all your work in navigating the complex real-world tradeoffs involved in work that treats fairness as a sociotechnical challenge! 👍

**Comment by romanlutz** [comment]
> In working forward on this, I thought it was important to bring up that while the open source Fairlearn project may choose to focus on consumer lending as an example, this [microsoft.com article about Fairlearn](https://customers.microsoft.com/en-US/story/809460-ey-partner-professional-services-azure-machine-learning-fairlearn) presents quite a different context. The lead quote is that:
> 
> > We see... our partnership with Microsoft as critical to driving increased adoption and acceptance of AI from the regulators.
> 
> The article describes using Fairlearn on "real mortgage adjudication data" and not consumer loans. The regulatory context is ambiguous in the article, but in the US this difference matters since different federal regulations apply to mortgage lending.
> 
> Further, there's another important bit of context on mortgage lending to consider that specifically relates to third-party algorithmic systems. Last summer, the US Department of Housing and Urban Development proposed a rule change that would make specific regulatory exceptions for mortgage lending decisions that are made by third party algorithmic systems. Some familiar names have submitted [public comments](https://twitter.com/aselbst/status/1185232906148601856) and written [articles](https://slate.com/technology/2019/08/hud-disparate-impact-discrimination-algorithm.html) on this. Here's an excerpt from the article by Andrew Selbst (with my emphasis added):
> 
> > [The] new proposed rule... [would] give landlords and mortgage lenders a recipe to discriminate by algorithm... First, the proposal allows landlords to use an algorithm as long as its inputs are not “substitutes or close proxies” for protected characteristics and as long as it’s predictive of what it purports to predict—or a “neutral third party” certifies that fact... Second, the landlord is also immunized from any discrimination claim **if he uses a tool developed and maintained by a recognized third party.** These safe harbors supposedly ensure that a model is legitimate and the landlord has not himself “caused” the discriminatory outcome.
> 
> And an excerpt from the [public comments](https://twitter.com/aselbst/status/1185232906148601856) by Selbst and Gilman:
> 
> > Permitting a defense showing that the model is the fault of some third party that determines industry standards creates functional immunity because there is no mention that the industry standard be anti-discriminatory, and the third party likely cannot be sued under the Fair Housing Act. Permitting “an objective and unbiased neutral third party” to validate the truth of the first defense and that the algorithm is “statistically sound” fails to account for algorithmic discrimination for the same reason the first defense does. Though the NPRM claims that the “section is not intended to provide a special exemption for parties who use algorithmic models,” 84 Fed. Reg. 42859, that is precisely the effect of the rule as written.
> 
> So when considering this context, and thinking about how Fairlearn might be able to contribute to assessing and mitigating real world harms for real people in the context of fair lending, I interpret the [microsoft.com article about Fairlearn](https://customers.microsoft.com/en-US/story/809460-ey-partner-professional-services-azure-machine-learning-fairlearn) a bit differently.
> 
> I am sure there is a ton of complexity in all of this work, but @MiroDudik @hannawallach if these were not things you'd come across yet, I thought it might be helpful to raise them for your consideration. While @MiroDudik I heard you suggesting that a notebook for Fairlearn might be better suited for consumer lending, and that might make a good first deployment context to focus on, I think it's important to say that the current marketing of Fairlearn has actually been aimed at mortgage lending.
> 
> Thanks for listening, and for all your work in navigating the complex real-world tradeoffs involved in work that treats fairness as a sociotechnical challenge! 👍

This is interesting context. In your comments there seems to be an assumption that we need to pick the scenario that matches an article. From what I understood last time we're pretty flexible in which application we want to choose. Perhaps pointing out differences to consider between the applications is useful for readers (personal loan vs. mortgage vs. credit card etc.). I also wonder to what extent we should be careful about focusing too much about specific laws since they tend to change quite a bit these days.

**Comment by kevinrobinson** [comment]
From the conversation today, we're going to close this and try another angle at finding a specific deployment context.

**Comment by kevinrobinson** [comment]
I believe this became https://www.microsoft.com/en-us/research/uploads/prod/2020/09/Fairlearn-EY_WhitePaper-2020-09-22.pdf.

**Pull request closed without merging**
