### PR TITLE
Revert "MNT Post-v0.6.2 release adjustments (#775)"

### PR DESCRIPTION
**Pull request by romanlutz**
This reverts commit 9e07dd2b1ef4248d1f1a29c391beeb278c24984d.

It was prematurely merged. The release has to happen first.

### CODE REVIEW

**Review by MiroDudik — APPROVED** [review]

**Review by riedgar-ms — APPROVED** [review]

**Comment by romanlutz** [comment]
@MiroDudik will instead fix the website repo directly

**Comment by adrinjalali** [comment]
We really need to fix the doc build

**Comment by romanlutz** [comment]
I assume by this you mean that it should automagically take the latest version, rather than us hardcoding versions, right?
I temporarily fixed it in the website repo by pushing to the main branch there (it's still called "master"), but the next merged PR will undo that.

**Comment by romanlutz** [comment]
We could also do something similar to scikit-learn and point to the latest release, rather than hardcoding it every time.

**Comment by MiroDudik** [comment]
Yes--hard-coding is extremely brittle for many reasons.

**Pull request closed without merging**
