### PR TITLE
DOC remove notebooks

### LINKED ISSUE #1175: DOC remove the last .ipynb notebook
Is it time to remove the very last .ipynb notebook from our repository?
https://github.com/fairlearn/fairlearn/blob/main/notebooks/Grid%20Search%20for%20Binary%20Classification.ipynb

Or do we believe it serves some educational value that would be lost?

### PR DESCRIPTION
**Pull request by MiroDudik**
Remove notebooks and the related baggage in our testing scripts and dependencies. Closes #1175

### CODE REVIEW

**Review by romanlutz — APPROVED** [review]
Thanks!

**Comment by MiroDudik** [comment]
> There were also a bunch of related scripts in the azure CI code, should we now remove all of those too?

I tried to do that too--that's why 9 files are affected :-)... let me know if i missed any. @riedgar-ms?

**Comment by riedgar-ms** [comment]
We should be off Azure CI now @adrinjalali ; we could probably remove the whole `devops` directory. However, I don't see anything obviously related to notebooks left in `scripts/`

**Review by riedgar-ms — APPROVED** [review]

**Comment by MiroDudik** [comment]
> We should be off Azure CI now @adrinjalali ; we could probably remove the whole `devops` directory. However, I don't see anything obviously related to notebooks left in `scripts/`

I can remove devops in this PR if that's okay with folks?

**Pull request merged**
