### PR TITLE
[DOC] List valid transforms for make_derived_metric

### PR DESCRIPTION
**Pull request by Carlosbogo**
Added the list of possible options for the transformation parameter in make_derived_metric API ref.

### CODE REVIEW

**Comment by hildeweerts** [comment]
Hi @Carlosbogo, thank you for having a go at this! 

It seems there is a trailing whitespace on line 135, which is why flake8 is complaining. Could you remove it? 
Additionally, we try to keep the line length to a maximum of 79 characters (although we haven't been super consistent with this throughout the repository).

Thanks!

**Comment by riedgar-ms** [comment]
Thank you for working on this! I've changed the PR name to be a little more explanatory.

**Comment by Carlosbogo** [comment]
Hi, is there anything wrong with the PR that keeps it from being merged?
If there are any changes that should be made or anything I have done wrong, please tell me so and I will be glad to help.

**Comment by hildeweerts** [comment]
Hi @Carlosbogo - thank you for pinging - I did not realize you had made the required changes. I needed to merge main into your branch before I could merge, but once the gates pass @fairlearn/fairlearn-maintainers feel free to merge.

Thanks again for your contribution!

**Comment by romanlutz** [comment]
I'll take @hildeweerts' comment as an approval and will merge this. Thanks for adding this information to the docs, @Carlosbogo!

**Pull request merged**
