### PR TITLE
DOC move changelog to the website

### PR DESCRIPTION
**Pull request by romanlutz**
This is a first step towards #738.
The contents are not changed other than formatting & typo fixes. For versions where a migration guide existed the migration guide was appended to the version changelog.
This PR also removes numbering from the user guide since section names like "4.2.1 v0.4.6" are completely unreadable. If you have objections please voice them!  
Finally, the release instructions needed to be updated slightly to reflect this new changelog location.

### CODE REVIEW

**Comment by adrinjalali** [comment]
Awesome work @romanlutz , I'd be even happy with having all _older_ files to be together rather than separate, but you've done it all already.

I think installation guide is not of the same _level_ of importance compared to change log. I'm happy if the change log is a bit harder to reach compared to installation guide.

**Comment by romanlutz** [comment]
> Awesome work @romanlutz , I'd be even happy with having all _older_ files to be together rather than separate, but you've done it all already.
> 
> 
> 
> I think installation guide is not of the same _level_ of importance compared to change log. I'm happy if the change log is a bit harder to reach compared to installation guide.

This is just a first pass. In the future I hope to add
- list of PRs that got merged similar to sklearn (should be updated in every PR)
- release highlights (sort of what we have right now, but with more details)
- credit to the release manager (that is so far mostly @riedgar-ms 🙂 )
- potentially credit to people who participated in filing and discussing issues when they get closed
- anything else people want to include

So that means some extra content per release and lots of these files will be a bit more substantial than they are now and would warrant their own file(s).

Is there anything you want me to do regarding the second part (re installation guide)? I agree 100%. @shimst3r added this entire section recently 🥳

**Review by riedgar-ms — APPROVED** [review]

**Comment by romanlutz** [comment]
@adrinjalali if this works for you as a first version please merge. I'll be iterating on this in follow-up PRs as mentioned earlier.

**Comment by romanlutz** [comment]
Yes! This is what it looks like right now: https://fairlearn.org/main/user_guide/installation_and_version_guide/v0.7.0.html

There's definitely something off in the way the list on the bottom left is rendered but it doesn't really affect anything much
image

**Pull request merged**
