### PR TITLE
DOC Add note about MetricFrame CSV export

### PR DESCRIPTION
**Pull request by riedgar-ms**
Add to the `MetricFrame` example, to draw attention to the ability to export to a CSV file.

### CODE REVIEW

**Comment by riedgar-ms** [comment]
Tagging @michaelamoako who highlighted this originally.

**Review by romanlutz — APPROVED** [review]
LGTM!

**Comment by riedgar-ms** [comment]
> LGTM! I assume you checked the output in the generated docs?

Hmmm.... I was building locally and it was fine. However, in the docs on circleci, the change is absent:
https://3303-133444044-gh.circle-artifacts.com/0/docs/_build/html/main/auto_examples/plot_new_metrics.html

I have dim memories of this happening sometime before?

**Comment by romanlutz** [comment]
@riedgar-ms yes CircleCI doesn't pick up the branch anymore, but it's entirely unclear why since we didn't change anything and CircleCI actually claims to check out the PR branch. I've spent about 3 hours on it and couldn't get anywhere... just ignore if the local build works fine.

**Comment by riedgar-ms** [comment]
Local build worked for sure.... @adrinjalali  @MiroDudik  @hildeweerts any comments?

**Pull request merged**
