### PR TITLE
Update Doc Build

### PR DESCRIPTION
**Pull request by riedgar-ms**
## Description

Since we are using a new release process (particularly our release branch naming convention), we need to tweak the documentation push to match.

## Tests

- [x] no new tests required
- [ ] new tests added
- [ ] existing tests adjusted

## Documentation

- [x] no documentation changes needed
- [ ] user guide added or updated
- [ ] API docs added or updated
- [ ] example notebook added or updated

### CODE REVIEW

**Comment by riedgar-ms** [comment]
@adrinjalali I'm unsure about the changes you mentioned to the bash script in the other thread. The highlighted change appears to just strip the last two characters off the branch name, which will still work if it is just `.X`. However, looking in the `fairlearn.github.io` repo, the directories appear to have their names fully intact. I'm not quite sure what's going on.

**Comment by riedgar-ms** [comment]
BTW @adrinjalali I'm moving the script since, with the move away from ADO, it might be best to just delete the `devops` directory.

**Comment by riedgar-ms** [comment]
> > However, looking in the fairlearn.github.io repo, the directories appear to have their names fully intact. I'm not quite sure what's going on.
> 
> I only had pushed to `main`, those other folders I didn't touch. So basically, this part of the script is never tested on our repo.

Ahhh OK. The joys of debugging processes you only do occasionally :-/

So this will likely push us a `release/v0.8` directory in the docs repo.... so I need to figure out how to remove the first portion of that.  And fix `landing_page.js` and `versions.json`.

**Comment by adrinjalali** [comment]
Yes, that's what I meant by removing the first part :) :D

**Comment by riedgar-ms** [comment]
Am I missing anything @adrinjalali ?

**Review by adrinjalali — APPROVED** [review]
This looks about right!

**Pull request merged**
