### PR TITLE
changed html_logo

### PR DESCRIPTION
**Pull request by svenkat19**

### CODE REVIEW

**Comment by hildeweerts** [comment]
Hi @svenkat19, thank you for the PR!

Did you build the website locally to verify whether the logo shows up? Could you please add a screenshot so we can check that it looks as expected?

PS. We usually add to a description something like "closes #...", "fixes #...", or "resolves #..." with the number of the associated issue. In that way the issue gets closed automatically when we merge the PR (more info [here])https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

**Comment by svenkat19** [comment]
> Hi @svenkat19, thank you for the PR!
> 
> Did you build the website locally to verify whether the logo shows up? Could you please add a screenshot so we can check that it looks as expected?
> 
> PS. We usually add to a description something like "closes #...", "fixes #...", or "resolves #..." with the number of the associated issue. In that way the issue gets closed automatically when we merge the PR (more info [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword))

Could you please help me out on how to build the website, I am quite new to this!

**Comment by hildeweerts** [comment]
Sure! 

You first need to make sure that you have installed the packages that are required to build the documentation. You can find these in [this file](https://github.com/fairlearn/fairlearn/blob/main/requirements-dev.txt) but you can also install them all automatically using the python script as described in the first paragraph of [this page](https://fairlearn.org/v0.7.0/contributor_guide/contributing_documentation.html).

Then you can run `make doc` from the root directory of the fairlearn repository after which the website is generated in the `docs/_build` directory. This will take a while, usually around 15min if it's the first time you're building the website.

I hope this helps - let me know if you have any further questions!

**Comment by svenkat19** [comment]
> Sure!
> 
> You first need to make sure that you have installed the packages that are required to build the documentation. You can find these in [this file](https://github.com/fairlearn/fairlearn/blob/main/requirements-dev.txt) but you can also install them all automatically using the python script as described in the first paragraph of [this page](https://fairlearn.org/v0.7.0/contributor_guide/contributing_documentation.html).
> 
> Then you can run `make doc` from the root directory of the fairlearn repository after which the website is generated in the `docs/_build` directory. This will take a while, usually around 15min if it's the first time you're building the website.
> 
> I hope this helps - let me know if you have any further questions!

image
I built the website. Is this okay??

**Comment by hildeweerts** [comment]
Hmm.. it seems my proposed solution was not the correct one... When we change the url like this the image cannot be found while building the docs - I got this warning: `WARNING: logo file '/images/fairlearn_full_color.png' does not exist`. I will update the issue and think a bit further on how this might be solved.

**Comment by hildeweerts** [comment]
Hi @svenkat19. It turns out that this is an issue with sphinx that can be fixed by updating to sphinx 4.1.1 once the folks at sphinx release that version (see my updates to #899). 

I am so sorry for not checking this in more detail before assigning the issue to you! :( I do hope that it was a good learning experience for you, despite the perhaps disappointing outcome.

I will close this PR now as it is no longer necessary.

**Pull request closed without merging**
