### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by srayagarwal**
Added two notebooks with small chunks

### CODE REVIEW

**Comment by srayagarwal** [comment]
Please review

**Comment by srayagarwal** [comment]
Signed-off-by: Sray Agarwal

**Comment by romanlutz** [comment]
@srayagarwal PRs should always be as small as possible, so please try not to submit all of these at once in a single PR. Perhaps we can start with a single notebook?

A few other notes:
- There's a notebooks directory. All notebooks can go there for now until we reorganize the structure of the documentation (see fairlearn-proposals repository for more info).
- Under test/notebooks there's a file that adds notebooks to tests. Add your notebook there, too, to make sure we always validate it before check-ins. Otherwise it can get out of sync with the repository and then users have issues replicating your example.
- If you use any new packages that aren't installed by default (I think I saw seaborn) then they'll need to be added to requirements.txt, otherwise our CI won't have it and fail.
- I don't think we want to duplicate metric functionality in the repository. Miro's PR #379 is almost completed (should be checked in on Monday), at which point I'd encourage you to consider replacing `fair_func` usage in your notebook with `fairlearn.metrics` code. If you have questions about that let me know. If there are metrics we haven't implemented yet we can either see whether we want to add them, or whether your notebook should contain the implementation.

**Comment by srayagarwal** [comment]
signoff by Sray Agarwal

**Comment by romanlutz** [comment]
> 
> 
> signoff by Sray Agarwal

if you're struggling with DCO I recommend following the description in CONTRIBUTING.md
We've have problems getting a failing DCO to pass, so sometimes it's easier to just recreate the PR after making sure your IDE or git are configured correctly to auto-add the signature.

**Comment by srayagarwal** [comment]
Closed

**Pull request closed without merging**
