### PR TITLE
Made navigation bar consistent on front page

### PR DESCRIPTION
**Pull request by Gingeh**
#825

### CODE REVIEW

**Comment by MiroDudik** [comment]
@IllegalBeagle123 : Thanks for picking this up! The updates should be in the opposite direction though. The navbar of the static page is currently more vetted, whereas the navbar automatically generated by sphinx is more stale.

Sorry about this, we should have made this clear in #825.

@hildeweerts @LeJit @romanlutz

**Review by MiroDudik — CHANGES_REQUESTED** [review]
[see the [comment above](https://github.com/fairlearn/fairlearn/pull/829#issuecomment-850845492)]

**Comment by MiroDudik** [comment]
@Gingeh: We've realized that this might actually not be the best first issue since it requires mucking with how sphinx renders the navigation bar (I have removed the "good first issue" tag). Sorry about that. Please let us know if you'd like to continue with this PR.

**Comment by romanlutz** [comment]
Closing this since there's been no response. If you're still interested please reopen and comment. We can sync on specifics if you'd like.

**Comment by romanlutz** [comment]
Reopening since the associated PR wasn't merged as it preceded @MiroDudik's more specific instructions (on fixing the bar in all the other pages to make it consistent with the landing page, rather than the other way round). This is up for grabs for anyone who'd like to try! Just comment below.

**Pull request closed without merging**
