### PR TITLE
DOC add Allie as maintainer!

### PR DESCRIPTION
**Pull request by romanlutz**
## Description

Adding @alliesaizan to @fairlearn/fairlearn-maintainers ! 🙂 

## Tests

- [x] no new tests required
- [ ] new tests added
- [ ] existing tests adjusted

## Documentation

- [ ] no documentation changes needed
- [ ] user guide added or updated
- [ ] API docs added or updated
- [ ] example notebook added or updated

### CODE REVIEW

**Comment by romanlutz** [comment]
Looks like the issue I'm fixing in https://github.com/fairlearn/fairlearn/pull/1282 is blocking the gates. Happy to override but we can also wait until https://github.com/fairlearn/fairlearn/pull/1282 is merged.

**Comment by alliesaizan** [comment]
> Looks like the issue I'm fixing in #1282 is blocking the gates. Happy to override but we can also wait until #1282 is merged.

Either way is fine! Happy to join the team.

**Comment by adrinjalali** [comment]
(@romanlutz could you pretty please remove the remote with write access to the main repo from your clone? You created a branch on the main repo again)

**Comment by romanlutz** [comment]
> (@romanlutz could you pretty please remove the remote with write access to the main repo from your clone? You created a branch on the main repo again)

Will look into this today. I actually created this from the browser by hitting edit, and was hoping it would offer me the option of creating the branch in my fork, but, alas, it did not...
Stay tuned!

**Comment by hildeweerts** [comment]
Still catching up after my vacation, but YAAAAY!!

**Pull request merged**
