### PR TITLE
Fix Windows notebook tests for  python 3.5 & 3.6 build by adding special case for BGL test case back

### PR DESCRIPTION
**Pull request by romanlutz**
This was there previously but we thought it was fixed. Will need to validate with nightly builds to make sure it works.

Related to #265 but does not fix it :-(

### CODE REVIEW

**Comment by adrinjalali** [comment]
just a reminder that according to NEP29 python3.5 is no more supported by the scipy ecosystem. Pandas, matplotlib, and the coming scikit-learn have already all dropped support for 3.5

**Comment by riedgar-ms** [comment]
I would not be averse to dropping py3.5 (and probably adding py3.8...). @MiroDudik ? @romanlutz ?

**Comment by romanlutz** [comment]
There's another issue in the nightly builds. The Windows py3.5 and py3.6 notebook pipelines fail due to a tolerance issue. I've upped the tolerance to 0.08 from 0.04 and they pass now. I wonder whether the base value 0.35 is off by a little or whether something on these platforms just works differently....

**Comment by romanlutz** [comment]
> 
> 
> I would not be averse to dropping py3.5 (and probably adding py3.8...). @MiroDudik ? @romanlutz ?

I don't mind that at all, but you may want to factor in that you're trying to use this package in other packages that may rely on having py3.5? Not sure to what extent that should be a consideration for an open source project, but I want to point this out at least

**Comment by romanlutz** [comment]
> 
> 
> > I would not be averse to dropping py3.5 (and probably adding py3.8...). @MiroDudik ? @romanlutz ?
> 
> I don't mind that at all, but you may want to factor in that you're trying to use this package in other packages that may rely on having py3.5? Not sure to what extent that should be a consideration for an open source project, but I want to point this out at least

This was also failing for python 3.6 on Windows (notebooks only), so the pinning of papermill is required regardless.

**Pull request merged**
