### PR TITLE
MNT deprecation and future warnings

### PR DESCRIPTION
**Pull request by eskayML**
Made an attempt at issue #848

### CODE REVIEW

**Comment by romanlutz** [comment]
We'd probably want this in other pipelines, not necessarily the website build.

**Comment by eskayML** [comment]
I have a question

So lets assume i'm to implement this on all pipelines. 

Am I to edit the `setup.cfg` file instead and add something like 

```bash
[pytest]
addopts = -Werror::DeprecationWarning -Werror::FutureWarning
```

**Comment by romanlutz** [comment]
Oooh that's interesting! I hadn't heard of this but that seems perfect. Maybe run it locally to make sure it succeeds. We may need to fox a few things before that can become the rule 🙂 if it does fail please post the output and we can open an issue for that.

**Comment by eskayML** [comment]
This is what i'm having



Screenshot (7)

**Comment by romanlutz** [comment]
That is mostly due to not having pytest matplotlib (mpl) installed. 

Those tests don't currently work on the build agents for reasons I haven't quite figured out yet. Probably something to do with how mpl uses OS-specific tools to create its images.

Is there a way to ignore individual issues like this?

**Comment by adrinjalali** [comment]
Closing since #1171 has resolved the issue. Thanks for the contribution @eskayML . Sorry for this being resolved somewhere else.

**Pull request closed without merging**
