### PR TITLE
Adding custom template for classes and revised API reference index file

### PR DESCRIPTION
**Pull request by alliesaizan**
## Description
This PR references issue #1243, fixing the issue where the links to class methods and attributes do not render in the API documentation. This PR makes two changes to the docs folder:
- Adds a _template directory, under which there is a custom template file for classes
- References that custom template file in the index file within api_reference

Let me know if there are questions/suggestions!

Tagging @hildeweerts @romanlutz 

## Tests
- [X] no new tests required
- [ ] new tests added
- [ ] existing tests adjusted

## Documentation
- [ ] no documentation changes needed
- [ ] user guide added or updated
- [X] API docs added or updated
- [ ] example notebook added or updated

## Screenshots
image

### CODE REVIEW

**Review by romanlutz — APPROVED** [review]
Awesome! Thanks @alliesaizan

**Comment by hildeweerts** [comment]
For some reason [these changes do not show up on CircleCI](https://output.circle-artifacts.com/output/job/fdbf91b2-42f1-4cdd-b6f7-8221b8ecc6b3/artifacts/0/docs/_build/html/api_reference/generated/fairlearn.metrics.MetricFrame.html). I cannot seem to figure out whether this is an issue with the PR or CircleCI. 

Any ideas? @romanlutz @alliesaizan

**Comment by alliesaizan** [comment]
> For some reason [these changes do not show up on CircleCI](https://output.circle-artifacts.com/output/job/fdbf91b2-42f1-4cdd-b6f7-8221b8ecc6b3/artifacts/0/docs/_build/html/api_reference/generated/fairlearn.metrics.MetricFrame.html). I cannot seem to figure out whether this is an issue with the PR or CircleCI.
> 
> Any ideas? @romanlutz @alliesaizan

Not sure, but I will look into this and hopefully have some insights in a few days!

**Comment by hildeweerts** [comment]
Many thanks @alliesaizan! I'll have another look tomorrow as well. Hope to get this in soon so we can get started with new release! :)

**Comment by alliesaizan** [comment]
I looked into this a bit and there appears to be a difference in the artifacts generated when CircleCI builds the docs versus when the docs are built locally.

CircleCI's artifacts for the metrics module are below:
image

And here is what I get when I build the files locally (using a Windows virtual environment with Python 3.11.3): 
image

In my local build, the methods of `MetricFrame` are rendered as subpages, whereas this is not the case in CircleCI. 

My guess is that CircleCI is not referencing the template file in __templates_ (a new directory I added in this PR), and consequently is defaulting to the standard method of sphinx rendering, which does not render class/attributes documentation if not specified. This leaves me with two questions:

1. Did I incorrectly specify the __templates_ directory when I pushed to my development branch? I have a high-level understanding of CI/CD, so maybe there is another way that folder should be named/added such that CircleCI catches it upon build.
2. Should the CircleCI setup somehow be changed so that it doesn't miss this new folder?

I will keep looking into this but would appreciate insights on any of the above!

**Comment by hildeweerts** [comment]
The changes did not work locally for me either, but moving the custom template to an autosummary folder did the trick. Let's see if it also works for CircleCI!

**Comment by hildeweerts** [comment]
So that did not work either, unfortunately.

@romanlutz @adrinjalali do you have an idea why CircleCI could be inconsistent with local builds?

**Comment by hildeweerts** [comment]
> Taking a step back: should it really be a separate page per method of MetricFrame? I would argue not...
The [current output from CircleCI](https://output.circle-artifacts.com/output/job/b3f321f9-e50e-46dc-8b1c-768f591429fc/artifacts/0/docs/_build/html/api_reference/generated/fairlearn.metrics.MetricFrame.html) looks the same as [what we have deployed](https://fairlearn.org/main/api_reference/generated/fairlearn.metrics.MetricFrame.html) which looks fine to me. What am I missing?

See #1243 - the problem is that the API docstrings of the methods are not rendered anywhere right now. E.g., in the [current API ref](https://fairlearn.org/v0.8/api_reference/fairlearn.metrics.html#fairlearn.metrics.MetricFrame.difference) the documentation explains different options for `method` etc., in the output of CircleCI that information is gone.

**Comment by hildeweerts** [comment]
It would probably be better to have the methods rendered on the class page itself, rather than having separate pages, but this was the easiest solution @alliesaizan could find.

**Comment by adrinjalali** [comment]
doesn't seem like we're doing anything crazy on circleci though: https://github.com/fairlearn/fairlearn/blob/main/.circleci/config.yml not sure why they'd be different

**Comment by hildeweerts** [comment]
hmm... I was hoping maybe I was missing something obvious in our CircleCI config. I'm not really sure how to proceed. Could it be a version-related issue somehow (which I would find strange because even in a "fresh" environment the changes show up in my local build)

**Comment by romanlutz** [comment]
I can repro this as it is in CircleCI with a new conda env. Can one of you, @hildeweerts  and @alliesaizan , share your versions of the following Python packages (via `pip freeze`, for example):
```
numpy==1.25.1
numpydoc==1.5.0
pandas==2.0.3
pydata-sphinx-theme==0.12.0
pydocstyle==6.3.0
pypandoc==1.11
scikit-learn==1.3.0
scipy==1.11.1
Sphinx==4.5.0
sphinx-autodoc-typehints==1.19.1
sphinx-gallery==0.13.0
sphinxcontrib-applehelp==1.0.4
sphinxcontrib-bibtex==2.5.0
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
```

**Comment by hildeweerts** [comment]
It's the exact same 😅 

Could it be an OS issue then? I'm using macOS Ventura Version 13.4.1

**Comment by alliesaizan** [comment]
> 

@romanlutz here's my list. I am on a Windows 10 x64 computer. I did an update of python and ran install_packages.py in a clean conda env, but if it ends up being an OS issue I also have a Mac and I can try updating the PR again from that computer? 

```
numpy==1.25.1
numpydoc==1.5.0
pandas==2.0.3
pydata-sphinx-theme==0.12.0
pydocstyle==6.3.0
pypandoc==1.11
scikit-learn==1.3.0
scipy==1.11.1
Sphinx==4.5.0
sphinx-autodoc-typehints==1.19.1
sphinx-gallery==0.13.0
sphinxcontrib-applehelp==1.0.4
sphinxcontrib-bibtex==2.5.0
sphinxcontrib-devhelp==1.0.2
sphinxcontrib-htmlhelp==2.0.1
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==1.0.3
sphinxcontrib-serializinghtml==1.1.5
```

**Comment by romanlutz** [comment]
Alright, so it's probably not a version issue, that's great!

I've been fiddling with settings for longer than I care to admit 😅 BUT I think I found the fix. I'm not entirely sure if I can explain WHY it's needed, though. My initial hunch was to compare everything with sklearn, but they are basically identical, including the template. After reading the documentation for what things like `:members:` etc. do I felt like they're missing from our class template so I added them and voila!

image

I'll push those changes now.

FWIW I think having these on the same page is MUCH better than having a separate page, but I'm curious what @hildeweerts  and @alliesaizan think 😄

**Comment by hildeweerts** [comment]
Yesss - I like it a lot, many thanks for figuring this out @romanlutz!

**Comment by alliesaizan** [comment]
Yes, thank you @romanlutz!

**Pull request merged**
