### PR TITLE
Final edits to boston housing documentation

### PR DESCRIPTION
**Pull request by alliesaizan**
Changes include slight grammatical adjustments to the datasets rst file and addition of the datasets section to the user guide index.

### CODE REVIEW

**Comment by alliesaizan** [comment]
@romanlutz - bringing the new PR to your attention (number 1,000!) but it's looking like the webpage build failed with "Received "killed" signal", does it have to be approved before the build webpage can complete?

**Comment by romanlutz** [comment]
Woohoo #1000 !!! Thanks for the quick turnaround @alliesaizan!
I looked at the build and I'm quite perplexed. I reran it, but got the same result. Running the same with the `main` branch succeeded, though. Locally everything passes, however, so that makes me wonder what's going on there... I'll try to get to the bottom of this, but if anyone has ideas on what might be wrong please don't hesitate to let me know!

**Comment by alliesaizan** [comment]
@romanlutz I don't have a first impression of what might be going wrong, but I will look into it as well and see if I can figure out what the issue is!

**Comment by romanlutz** [comment]
Looks like it succeeded now! I suppose it was a temporary issue with CircleCI...
@fairlearn/fairlearn-maintainers can someone merge this? I just approved...

**Review by romanlutz — APPROVED** [review]

**Comment by alliesaizan** [comment]
@romanlutz thank you so much for your help!

**Comment by romanlutz** [comment]
> @romanlutz thank you so much for your help!

I didn't actually do anything this time 😄 unless you count retrying...

**Pull request merged**
