### PR TITLE
Improve error for MetricFrame

### LINKED ISSUE #753: MetricFrame and multiple/named sensitive features
I was writing an example notebook, and I encountered something which I found strange. Basically, this works:

``` python
multi_metric = MetricFrame(
    {
        "average precision": skm.average_precision_score,
        "roc-auc": skm.roc_auc_score,
        "count": lambda x, y: len(x),
    },
    y_test,
    y_pred,
    sensitive_features=gender_test,
)
```

But this doesn't:

``` python
multi_metric = MetricFrame(
    {
        "average precision": skm.average_precision_score,
        "roc-auc": skm.roc_auc_score,
        "count": lambda x, y: len(x),
    },
    y_test,
    y_pred,
    sensitive_features={'gender': gender_test},
)
```
with error: 

    ValueError: If using all scalar values, you must pass an index

To me this error message is not clear at all, and I have no pandas DataFrames to have any indices in the first place. I don't think we should be failing in this case.

cc @riedgar-ms @MiroDudik 

Here's the whole notebook for reproducibility

<details>

``` python
# %%
# First we need to install the requirements:
# pip install model-card-toolkit scikit-learn matplotlib fairlear pandas

# %%
# Here we have all the imports required to run the rest of the script
import numpy as np
import sklearn.metrics as skm
from numpy.random import RandomState
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.experimental import enable_hist_gradient_boosting  # noqa
from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.decomposition import PCA
from sklearn.pipeline import make_pipeline
from fairlearn.metrics import MetricFrame

# %%
rng = RandomState(seed=42)

X_women, y_women = make_classification(
    n_samples=500,
    n_features=20,
    n_informative=4,
    n_classes=2,
    class_sep=1,
    random_state=rng,
)

X_men, y_men = make_classification(
    n_samples=500,
    n_features=20,
    n_informative=4,
    n_classes=2,
    class_sep=2,
    random_state=rng,
)

X_unspecified, y_unspecified = make_classification(
    n_samples=500,
    n_features=20,
    n_informative=4,
    n_classes=2,
    class_sep=0.5,
    random_state=rng,
)

X = np.r_[X_women, X_men, X_unspecified]
y = np.r_[y_women, y_men, y_unspecified]
gender = np.r_[["Woman"] * 500, ["Man"] * 500, ["Unspecified"] * 500].reshape(
    -1, 1
)
X_train, X_test, y_train, y_test, gender_train, gender_test = train_test_split(
    X, y, gender, test_size=0.3, random_state=rng
)

# %%
# Now we train a classifier on the data
clf = make_pipeline(PCA(n_components=4), HistGradientBoostingClassifier())
clf.fit(X_train, y_train)

# %%
# We can finally check the performance of our model for different groups.
y_pred = clf.predict_proba(X_test)[:, 0]
multi_metric = MetricFrame(
    {
        "average precision": skm.average_precision_score,
        "roc-auc": skm.roc_auc_score,
        "count": lambda x, y: len(x),
    },
    y_test,
    y_pred,
    sensitive_features={'gender': gender_test},
)
```

</details>

### PR DESCRIPTION
**Pull request by riedgar-ms**
Improves on the error message from `pandas.DataFrame.from_dict()` (used when processing the sensitive features). Catches the exception and raises a new one with a more helpful error message.

Closes #753

### CODE REVIEW

**Review by hildeweerts — APPROVED** [review]

**Review by romanlutz — APPROVED** [review]

**Comment by romanlutz** [comment]
LGTM! I'll leave it open for another day in case @adrinjalali has a comment since you added him, too.

**Comment by riedgar-ms** [comment]
> LGTM! I'll leave it open for another day in case @adrinjalali has a comment since you added him, too.

It's @adrinjalali 's bug, so he definitely needs to review.

**Review by adrinjalali — APPROVED** [review]
Thanks @riedgar-ms 

> LGTM! I'll leave it open for another day in case @adrinjalali has a comment since you added him, too.

Sometimes people are on holidays @romanlutz :P

**Comment by romanlutz** [comment]
> Thanks @riedgar-ms 
> 
> 
> 
> > LGTM! I'll leave it open for another day in case @adrinjalali has a comment since you added him, too.
> 
> 
> 
> Sometimes people are on holidays @romanlutz :P 

@adrinjalali I figured :-)  My excitement to get things done got me carried away a bit. Obviously there's no real problem with waiting for the right people to review. I hope you enjoyed your holidays!

**Pull request merged**
