### PR TITLE
DOC contributing: trim lines and add notes on signoff

### PR DESCRIPTION
**Pull request by adrinjalali**
This PR trims the lines in the contributing guide, and adds this note:

```
It basically means you need to sign off your commits with your `gpg` key,
meaning you need to have a key in your `gpg` setup, and then you can set that
key to be the default using the guidelines in [this
post](https://stackoverflow.com/questions/10161198/is-there-a-way-to-autosign-commits-in-git-with-a-gpg-key).
```

### CODE REVIEW

**Comment by adrinjalali** [comment]
lol, apparently my note is not working on my own commit. Let me see

**Comment by adrinjalali** [comment]
This solution works now, changed the note to point to the right git hook.

**Comment by romanlutz** [comment]
> 
> 
> This PR trims the lines in the contributing guide, and adds this note:
> 
> ```
> It basically means you need to sign off your commits with your `gpg` key,
> meaning you need to have a key in your `gpg` setup, and then you can set that
> key to be the default using the guidelines in [this
> post](https://stackoverflow.com/questions/10161198/is-there-a-way-to-autosign-commits-in-git-with-a-gpg-key).
> ```

Pardon the question but why are we trimming lines? :-)

**Comment by adrinjalali** [comment]
Kinda for the same reason the code is trimmed at 80 according to PEP8. It makes it much easier to review future changes to the doc, review code side by side, and also much easier to read.

At least on my editor, and the community I know, the lines are not wrapped at the end of the screen. When I opened this file, most of the text was outside the screen and I had to scroll to see it.

And since the rendered version is not affected with the trimming, it doesn't seem to be a high risk one :)

**Comment by romanlutz** [comment]
> 
> 
> Kinda for the same reason the code is trimmed at 80 according to PEP8. It makes it much easier to review future changes to the doc, review code side by side, and also much easier to read.
> 
> At least on my editor, and the community I know, the lines are not wrapped at the end of the screen. When I opened this file, most of the text was outside the screen and I had to scroll to see it.
> 
> And since the rendered version is not affected with the trimming, it doesn't seem to be a high risk one :)

Sidenote: we upped the limit to 99, see setup.cfg

I just fear that, unlike with code where we have flake8, there's no validation for this so it's going to get ignored in the future unless there's an actual check. I'm not fundamentally opposed to it, of course, but if you know of some validation for this that may be cheap to add lmk.

**Comment by adrinjalali** [comment]
> Sidenote: we upped the limit to 99, see setup.cfg

Oh, interesting :D 

It's not crucial to validate, since it's just a convenience on the documentation, and we can just violate and fix it with no consequences.

**Pull request merged**
